### ISSUE TITLE
Help! WHY IS IS FAILING?!?!!

### ISSUE THREAD

**Issue by kylerchin** [ansuz/dnssb#2]
I got this. Any dnssb command shows this:

        root@kylerchin-website:~/kylerschin-boboe/dnssb# dnssb show kylerchin.com
        error loading sodium bindings: Cannot find module 'sodium-native'
        falling back to javascript version.
                /usr/local/lib/node_modules/ssb-dns/node_modules/ssb-client/index.js:74
      throw explain(err, 'could not load manifest file')
      ^

        Error: could not load manifest file
            at /usr/local/lib/node_modules/ssb-dns/node_modules/ssb-client/index.js:74:13
            at Module.load (module.js:343:32)
            at Function.Module._load (module.js:300:12)
          Error: ENOENT: no such file or directory, open '/root/.ssb/manifest.json'
            at Error (native)
            at Object.fs.openSync (fs.js:549:18)
            at Object.fs.readFileSync (fs.js:397:15)
            at /usr/local/lib/node_modules/ssb-dns/node_modules/ssb-client/index.js:70:28
            at module.exports (/usr/local/lib/node_modules/ssb-dns/node_modules/ssb-client/index.js:76:5)
            at /usr/local/lib/node_modules/ssb-dns/index.js:62:9
            at /usr/local/lib/node_modules/ssb-dns/index.js:72:6
            at Object.<anonymous> (/usr/local/lib/node_modules/ssb-dns/index.js:178:2)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)
![image](https://user-images.githubusercontent.com/7539174/27255253-684ee050-534f-11e7-8db3-844adb2f3741.png)

**Comment by kylerchin** [comment]
nevermind. forgot to start ```sbot server```
